services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=task'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=thaopham123'
      - 'MYSQL_USER=thaopham'
    ports:
      - '3307:3306'
